/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_seczone_ClassMethodExtractor */

#ifndef _Included_cn_seczone_ClassMethodExtractor
#define _Included_cn_seczone_ClassMethodExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_seczone_ClassMethodExtractor
 * Method:    nativeParseClassFile
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_cn_seczone_ClassMethodExtractor_nativeParseClassFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
